# Generated by Django 2.1.8 on 2019-04-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190408_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='omdb_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
